package mx.edu.uaz.SistemaControlEscolar.Design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MateriasDesign extends CssLayout {
	protected TextField tfAsignatura;
	protected TextField tfCreditos;
	protected ComboBox<mx.edu.uaz.SistemaControlEscolar.modelos.Programa> cboPrograma;
	protected ComboBox<mx.edu.uaz.SistemaControlEscolar.modelos.Materia> cboMateriaAnt;
	protected Button btnGuardar;
	protected Button btnCancelar;

	public MateriasDesign() {
		Design.read(this);
	}
}
