package mx.edu.uaz.SistemaControlEscolar.Design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.DateField;
import com.vaadin.ui.Image;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Upload;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class UsuarioAltaDesign extends CssLayout {
	protected TextField tfNombre;
	protected TextField tfApellidoPaterno;
	protected TextField tfApellidoMaterno;
	protected DateField dfFechaNac;
	protected ComboBox<mx.edu.uaz.SistemaControlEscolar.modelos.Estado> cboEstado;
	protected TextField tfMail;
	protected TextField tfUsuario;
	protected PasswordField pfPassword;
	protected CssLayout cssLFoto;
	protected Upload upFoto;
	protected Image imgFotoAlta;
	protected Button btnRegistrar;
	protected Button btnCancelar;

	public UsuarioAltaDesign() {
		Design.read(this);
	}
}
